version: "3.9"

networks:
  nids-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

services:
  protected:
    build: ../target
    container_name: protected
    networks:
      - nids-net

  attacker:
    build: ../attacker
    container_name: attacker
    networks:
      - nids-net

  snort:
    build: ../snort
    container_name: snort
    network_mode: service:protected
    cap_add:
      - NET_ADMIN
    volumes:
      - ../snort/config:/etc/snort
      - ../snort/rules:/etc/snort/rules
      - ../snort/logs:/var/log/snort
    depends_on:
      - protected

  log-viewer:
    build: ../log-viewer
    container_name: log-viewer
    networks:
      - nids-net
    volumes:
      - ../snort/logs:/var/log/snort
    depends_on:
      - snort
